//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ananya.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NTPCBD2Entities : DbContext
    {
        public NTPCBD2Entities()
            : base("name=NTPCBD2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_menu> Tbl_menu { get; set; }
        public virtual DbSet<Tbl_menu_role_mapping> Tbl_menu_role_mapping { get; set; }
        public virtual DbSet<Tbl_role> Tbl_role { get; set; }
        public virtual DbSet<Tbl_user> Tbl_user { get; set; }
        public virtual DbSet<Tbl_idea> Tbl_idea { get; set; }
        public virtual DbSet<Tbl_status> Tbl_status { get; set; }
        public IEnumerable<object> Tbl_Status { get; internal set; }
    }
}
