//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ananya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_status()
        {
            this.Tbl_idea = new HashSet<Tbl_idea>();
        }
    
        public int ID { get; set; }
        public string Statusdescription { get; set; }
        public Nullable<bool> Activeflag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_idea> Tbl_idea { get; set; }
    }
}
