//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ananya.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_idea
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Area of Concern is required.")]
        public string AreaofConcern { get; set; }
        [Required(ErrorMessage = "Title is required.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Idea brief is required.")]
        public string Idea_brief { get; set; }
        public string Detail_modelling { get; set; }
        public string Attachment { get; set; }
        public string Submitted_by { get; set; }
        public Nullable<System.DateTime> Submitted_date { get; set; }
        public Nullable<int> Status { get; set; }
        public string Lastmodifiedby { get; set; }
        public Nullable<System.DateTime> Lastmodified { get; set; }
        public Nullable<bool> Activeflag { get; set; }
    
        public virtual Tbl_status Tbl_status { get; set; }
    }
}
