//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ananya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_menu_role_mapping
    {
        public int ID { get; set; }
        public Nullable<int> Role_id { get; set; }
        public Nullable<int> Menu_id { get; set; }
        public Nullable<bool> Activeflag { get; set; }
    }
}
