//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ananya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_user
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Empno { get; set; }
        public Nullable<int> Role { get; set; }
        public string Password { get; set; }
        public Nullable<int> Lastmodifiedby { get; set; }
        public Nullable<System.DateTime> Lastmodified { get; set; }
        public Nullable<bool> Activeflag { get; set; }
    }
}
